env:
  global:
    - CC_TEST_REPORTER_ID=99a95b4ed919fe2b4b5135b454126bc7c0fc92976cbe55e9b003124151d8e0a4

langauge: node_js

node_js:
  - 14.4.0

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test --silent
  - npm test -- --coverage  --silent

after_script:
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT
