export const expectedBFSResult = [
  { row: 3, col: 2 },
  { row: 2, col: 2 },
  { row: 4, col: 2 },
  { row: 3, col: 1 },
  { row: 1, col: 2 },
  { row: 2, col: 1 },
  { row: 5, col: 2 },
  { row: 4, col: 1 },
  { row: 2, col: 1 },
  { row: 4, col: 1 },
  { row: 3, col: 0 },
  { row: 0, col: 2 },
  { row: 1, col: 1 },
  { row: 1, col: 3 },
  { row: 1, col: 1 },
  { row: 2, col: 0 },
  { row: 5, col: 1 },
  { row: 5, col: 3 },
  { row: 5, col: 1 },
  { row: 4, col: 0 },
  { row: 2, col: 0 },
  { row: 4, col: 0 },
  { row: 0, col: 1 },
  { row: 0, col: 3 },
  { row: 0, col: 1 },
  { row: 1, col: 0 },
  { row: 0, col: 3 },
  { row: 1, col: 4 },
  { row: 1, col: 0 },
  { row: 5, col: 0 },
  { row: 5, col: 4 },
  { row: 5, col: 0 },
  { row: 0, col: 0 },
  { row: 0, col: 4 },
  { row: 0, col: 0 },
  { row: 0, col: 4 },
  { row: 2, col: 4 },
  { row: 1, col: 5 },
  { row: 4, col: 4 },
  { row: 5, col: 5 },
  { row: 0, col: 5 },
  { row: 3, col: 4 },
];

export const expectedPathResult = [
  { row: 3, col: 2 },
  { row: 4, col: 2 },
  { row: 5, col: 2 },
  { row: 5, col: 3 },
  { row: 5, col: 4 },
  { row: 4, col: 4 },
  { row: 3, col: 4 },
];
